name: <your_env_name>
channels:
  - bioconda
  - r
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - numpy=1.26.0
  - mpmath=1.3.0
  - pandas=2.1.1
  - scikit-learn=1.3.0
  - matplotlib=3.8.4
