name: unsupML
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - matplotlib=3.8.4
  - mpmath=1.3.0
  - numpy=1.26.0
  - pandas=2.1.1
  - python=3.12.4
  - scikit-learn=1.3.0
  - scipy=1.11.3
